-- MySQL Script generated by MySQL Workbench
-- Tue Jan  9 19:00:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_mercado_delas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_mercado_delas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mercado_delas` DEFAULT CHARACTER SET utf8 ;
USE `db_mercado_delas` ;

-- -----------------------------------------------------
-- Table `db_mercado_delas`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mercado_delas`.`tb_categorias` (
  `id_categoria` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo_categoria` VARCHAR(255) NOT NULL,
  `descricao_categoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mercado_delas`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mercado_delas`.`tb_usuarios` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha_usuario` VARCHAR(255) NOT NULL,
  `foto_usuario` VARCHAR(255) NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mercado_delas`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mercado_delas`.`tb_produtos` (
  `id_produtos` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(255) NOT NULL,
  `descricao_produto` VARCHAR(255) NOT NULL,
  `preco_produto` DECIMAL(6,2) NOT NULL,
  `quantidade_produto` INT NULL,
  `foto_produto` VARCHAR(255) NULL,
  `id_categoria` BIGINT NULL,
  `id_usuario` BIGINT NULL,
  PRIMARY KEY (`id_produtos`),
  INDEX `fk_tb_produtos_tb_categorias_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_tb_produtos_tb_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_tb_categorias`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db_mercado_delas`.`tb_categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produtos_tb_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_mercado_delas`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
